### ISSUE TITLE
Add a person's webid (solid id) to the contacts individual view pane

### ISSUE THREAD

**Issue by timbl** [solid/contacts-pane#18]
As a string the user can edit, (using the NamedNodeURIU form element probabvly)

**Comment by timbl** [comment]
This looks like a fairly straightforward user interface problem, but the logic behind it is remarkably non-obvious, as it it begs the question of to store webids in contacts.

- Just adding something like  `<#this> solid:webid <http://....foo> . `to a contact card seems obviously a logical thing to do 
-  Adding `vcard:url [ vcard:type "WebId"; value <https://...foo> ] . `is useful as it a round trips with for example the Mac AddressBook software.
- But in fact when you use a webid in a  group to in the ACL system, then that webid has to be used directly as the group member, like `<#freinds> vcard:hasMember <https://.... foo> `. So that doesn't connect immediately to the local contact data.
- You can use owl:sameAs to link the persons webID and the person in the  address book card, so you get that connection.  So you could use that also in the contact card itself as a record of the webid.

**Comment by timbl** [comment]
Maybe a local index of external webids would be a good idea.

**Comment by michielbdejong** [comment]
Right!
In order to build a people-picker for adding webId's into the ACL system, we need a way do determine if a given URI is a WebID. When I look through https://michielbdejong.solidcommunity.net/profile/card#me I can tell that I have a storage, an inbox, preferences, but I don't see any mention of webid-oidc. That means that given an addressbook  entry with pointers to both https://michielbdejong.com/#about and https://michielbdejong.solidcommunity.net/profile/card#me, there's no good way of knowing which one is usable in webid-oidc and which one is not.

So adding `<#this> solid:webid <http://identity.com/#foo> .` in the addressbook entry helps, but I would then also like to add
`<#foo> a solid:Webid .` to http://identity.com/ maybe?

I think the index should only be necessary if you have so many contacts that you can't load them all into rdflib at the same time?

**Comment by michielbdejong** [comment]
So given a URI that describes a human being,
is there a mechanism for determining whether that URI will be usable as a webid-oidc identity or not?

cc @RubenVerborgh @jaxoncreed @justinwb - maybe you remember?

**Comment by RubenVerborgh** [comment]
>  is there a mechanism for determining whether that URI will be usable as a webid-oidc identity or not?

All URIs can be usable within WebID-OIDC. All it takes is the profile document indicating trust for a certain OIDC provider via `solid:oidcIssuer`.

**Comment by michielbdejong** [comment]
That's the one, thanks. It seems to be missing from https://github.com/solid/node-solid-server/blob/master/default-templates/new-account/profile/card%24.ttl, I'll add it (back) there.
The people-picker for ACLs can check for that, and the contacts-pane can display an icon when it's present.

**Comment by RubenVerborgh** [comment]
The default is that, for a WebID of `https://xyz.abc/foo/bar#me`, `https://xyz.abc` is a trusted OIDC issuer.

It should also work for cases where the domains are different, however, this has been broken for over a year now on NSS.
For instance, my WebID is https://ruben.verborgh.org/profile/#me but my OIDC issuer is https://drive.verborgh.org

**Comment by timbl** [comment]
Has that been raised as an issue on NSS? Is it on a solid test suite so other servers will do it?

**Comment by RubenVerborgh** [comment]
@timbl Issue at https://github.com/solid/node-solid-server/issues/1244

Not aware of a test for this, but I will certainly keep this in mind as it prevents me from using Solid with my actual WebID.

**Comment by timbl** [comment]
But getting back to the issue, this is about me keeping track of my contacts' webids.   This has been done to date in a VCARD-compatible way:
```
:this  a vcard:Individual; 
   vcard:url [ a vcard:WebId; vcard:value "https://ruben.verborgh.org/profile/#me" ] .
```
This will then show up in your Apple contacts phone iPhone or Mac as 

  WebId: https://ruben.verborgh.org/profile/#me

and it can be added there too in the Contacts UI.

Yes, It is interesting that logically when you look up someone in their solid profile there is nothing to say that that is a webid.

**Comment by timbl** [comment]
But the issue of how I put public stuff about my own webid in my public profile is very close and overlapping.

Of course there is also in the [contacts ontology](https://www.w3.org/2000/10/swap/pim/contact.n3)
```
:preferredURI a rdf:Property;
    rdfs:label "preferred";
    rdfs:comment """A string which is the URI a person, organization, etc, prefers that people use for them.""".

```
Note is correctly talks about the string `"https://ruben.verborgh.org/profile/#me"` not the thing identified by the string `<https://ruben.verborgh.org/profile/#me>`

What is doesn't say is whether that string as a URI is good for.  Can I give you access to things in an ACL with it?   Can I make a new chat and ping your inbox about it?   For now we must just assume it can be used for all those.

**Comment by csarven** [comment]
Also raised this issue/need at https://gitter.im/solid/chat?at=59f890fce44c43700a9dc81f (2017) - see short conversation following. Tangentially related and what's in practice re linking an non-webid identifier with webid: https://csarven.ca/linked-research-decentralised-web#orcid-sameas-webid .. but it is actually missing the webid reference that I was looking for.

This is important because ( https://gitter.im/solid/chat?at=59aff8b8b16f264642106d19 , https://gitter.im/solid/chat?at=59f9ed634ff065ac18a211eb ) it can bootstrap existing ids to Solid stuff. So, apparently, I did propose `acl:owner` (or alike) to connect agents (the one that "owns", controls..)... which somehow made it into ACL vocab after all.

**Comment by timbl** [comment]
Closed - fixed in https://github.com/solid/contacts-pane/pull/23
